// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReyMagoApi.DataAccess;

#nullable disable

namespace ReyMagoAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221114010128_AddSeeds")]
    partial class AddSeeds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReyMagoApi.Entities.Afinidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Afinidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Oscuridad"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Luz"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fuego"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Agua"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Viento"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Tierra"
                        });
                });

            modelBuilder.Entity("ReyMagoApi.Entities.Estudiante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AfinidadId")
                        .HasColumnType("int");

                    b.Property<int>("Afinidad_id")
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Edad")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<bool>("Estatus")
                        .HasColumnType("bit");

                    b.Property<int>("GrimorioId")
                        .HasColumnType("int");

                    b.Property<int>("Grimorio_id")
                        .HasColumnType("int");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("AfinidadId");

                    b.HasIndex("GrimorioId");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("ReyMagoApi.Entities.Grimorio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Grimorios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Trébol de 1 hoja",
                            Name = "Sinceridad"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Trébol de 2 hoja",
                            Name = "Esperanza"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Trébol de 3 hoja",
                            Name = "Amor"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Trébol de 4 hoja",
                            Name = "Buena Fortuna"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Trébol de 5 hoja",
                            Name = "Desesperación"
                        });
                });

            modelBuilder.Entity("ReyMagoApi.Entities.Estudiante", b =>
                {
                    b.HasOne("ReyMagoApi.Entities.Afinidad", "Afinidad")
                        .WithMany("Estudiante")
                        .HasForeignKey("AfinidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReyMagoApi.Entities.Grimorio", "Grimorio")
                        .WithMany("Estudiante")
                        .HasForeignKey("GrimorioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Afinidad");

                    b.Navigation("Grimorio");
                });

            modelBuilder.Entity("ReyMagoApi.Entities.Afinidad", b =>
                {
                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("ReyMagoApi.Entities.Grimorio", b =>
                {
                    b.Navigation("Estudiante");
                });
#pragma warning restore 612, 618
        }
    }
}
